version: '3.8'

services:

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - vital-net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vital-net

  vitalapp:
    image: juanjothin/vitalapp:latest
    container_name: vitalapp
    ports:
      - "8081:8080" # Mapear puerto interno al host
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/vitalappdb
    networks:
      - vital-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: DockerFile
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vital-net

networks:
  vital-net:
    driver: bridge

volumes:
  mongodb_data:
  jenkins_home:
