version: '3.8'

services:

  # Base de datos requerida por SonarQube
  postgres:
    image: postgres:15
    container_name: sonardb
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    networks:
      - vital-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SonarQube (ahora conectado a PostgreSQL)
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    shm_size: '2gb'
    restart: unless-stopped
    networks:
      - vital-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vital-net

  vitalapp:
    image: juanjothin/vitalapp:latest
    container_name: vitalapp
    ports:
      - "8083:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/vitalappdb
    networks:
      - vital-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: DockerFile
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vital-net

networks:
  vital-net:
    driver: bridge

volumes:
  sonardb_data:
  sonarqube_data:
  sonarqube_extensions:
  mongodb_data:
  jenkins_home:
